from currency.currencyclass import AUDUSD_return
from currency.currencyclass import GBPEUR_return
from currency.currencyclass import USDCAD_return
from currency.currencyclass import USDJPY_return
from currency.currencyclass import USDMXN_return
from currency.currencyclass import EURUSD_return
from currency.currencyclass import USDCNY_return
from currency.currencyclass import USDCZK_return
from currency.currencyclass import USDPLN_return
from currency.currencyclass import USDINR_return
